[tool.poetry]
name = "bookmanagement"
version = "0.1.0"
description = ""
authors = ["Felix <flex89@web.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
sqlalchemy = "^2.0.40"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
